version: '3.1'

services:
  database:
    image: postgres:14.3-alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "hoggo"

  redis:
    image: redis:5.0.5
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes